# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adds/adds.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds || ORIG_REF_NAME==adds} -quiet] -quiet

# IP: bd/adds/ip/adds_axi_dma_0_0/adds_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_axi_dma_0_0 || ORIG_REF_NAME==adds_axi_dma_0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_axi_interconnect_0_0/adds_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_axi_interconnect_0_0 || ORIG_REF_NAME==adds_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_axi_interconnect_1_0/adds_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_axi_interconnect_1_0 || ORIG_REF_NAME==adds_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/adds/ip/adds_axis_adder_0_0/adds_axis_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_axis_adder_0_0 || ORIG_REF_NAME==adds_axis_adder_0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_ps7_0_0/adds_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_ps7_0_0 || ORIG_REF_NAME==adds_ps7_0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_rst_ps7_0_fclk0_0/adds_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==adds_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_rst_ps7_0_fclk1_0/adds_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==adds_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/adds/ip/adds_rst_ps7_0_fclk2_0/adds_rst_ps7_0_fclk2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_rst_ps7_0_fclk2_0 || ORIG_REF_NAME==adds_rst_ps7_0_fclk2_0} -quiet] -quiet

# IP: bd/adds/ip/adds_rst_ps7_0_fclk3_0/adds_rst_ps7_0_fclk3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_rst_ps7_0_fclk3_0 || ORIG_REF_NAME==adds_rst_ps7_0_fclk3_0} -quiet] -quiet

# IP: bd/adds/ip/adds_xlconcat_0_0/adds_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_xlconcat_0_0 || ORIG_REF_NAME==adds_xlconcat_0_0} -quiet] -quiet

# IP: bd/adds/ip/adds_xbar_0/adds_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_xbar_0 || ORIG_REF_NAME==adds_xbar_0} -quiet] -quiet

# IP: bd/adds/ip/adds_auto_pc_1/adds_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_auto_pc_1 || ORIG_REF_NAME==adds_auto_pc_1} -quiet] -quiet

# IP: bd/adds/ip/adds_auto_us_1/adds_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_auto_us_1 || ORIG_REF_NAME==adds_auto_us_1} -quiet] -quiet

# IP: bd/adds/ip/adds_auto_us_0/adds_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_auto_us_0 || ORIG_REF_NAME==adds_auto_us_0} -quiet] -quiet

# IP: bd/adds/ip/adds_auto_pc_0/adds_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adds_auto_pc_0 || ORIG_REF_NAME==adds_auto_pc_0} -quiet] -quiet

# XDC: bd/adds/adds_ooc.xdc
