# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/add/add.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add || ORIG_REF_NAME==add} -quiet] -quiet

# IP: bd/add/ip/add_axi_adder_0_0/add_axi_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_axi_adder_0_0 || ORIG_REF_NAME==add_axi_adder_0_0} -quiet] -quiet

# IP: bd/add/ip/add_axi_interconnect_0_0/add_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_axi_interconnect_0_0 || ORIG_REF_NAME==add_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/add/ip/add_ps7_0_0/add_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_ps7_0_0 || ORIG_REF_NAME==add_ps7_0_0} -quiet] -quiet

# IP: bd/add/ip/add_rst_ps7_0_fclk0_0/add_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==add_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==add_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/add/ip/add_rst_ps7_0_fclk2_0/add_rst_ps7_0_fclk2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_rst_ps7_0_fclk2_0 || ORIG_REF_NAME==add_rst_ps7_0_fclk2_0} -quiet] -quiet

# IP: bd/add/ip/add_rst_ps7_0_fclk3_0/add_rst_ps7_0_fclk3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_rst_ps7_0_fclk3_0 || ORIG_REF_NAME==add_rst_ps7_0_fclk3_0} -quiet] -quiet

# IP: bd/add/ip/add_xlconcat_0_0/add_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_xlconcat_0_0 || ORIG_REF_NAME==add_xlconcat_0_0} -quiet] -quiet

# IP: bd/add/ip/add_auto_pc_0/add_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_auto_pc_0 || ORIG_REF_NAME==add_auto_pc_0} -quiet] -quiet

# XDC: bd/add/add_ooc.xdc
