# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0.xci
# IP: The module: 'add_rst_ps7_0_fclk1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0.xci
# IP: The module: 'add_rst_ps7_0_fclk1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/add/add/add.srcs/sources_1/bd/add/ip/add_rst_ps7_0_fclk1_0/add_rst_ps7_0_fclk1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_rst_ps7_0_fclk1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
