# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0.xci
# IP: The module: 'adds_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'adds_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adds_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0.xci
# IP: The module: 'adds_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'adds_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/RISC-V/Pynq_Proj/Projects/Yun/yun_repo/PYNQ-adder/boards/Pynq-Z1/adds/adds/adds.srcs/sources_1/bd/adds/ip/adds_auto_us_0/adds_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adds_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
